[package]
name = "machinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = { version = "0.32.1", features = ["serde"] }
