[package]
name = "machinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = { version = "0.32.1", features = ["serde"] }

[build-dependencies]
chrono = "0.4"
